### ISSUE TITLE
"custom" extractor assumes a "Multipoint" return

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/marklogic-geo-data-services#20] opened 2019-09-04 20:23 UTC
The "custom" extractor pulls data from a configured index. The GeoJSON that is returned has a type of "Multipoint" which koop does not return to the client. The Koop client makes use of a "Point" return type instead of "Multipoint".

Code link: https://github.com/marklogic-community/marklogic-geo-data-services/blob/master/src/main/ml-modules/ext/geo/extractor.sjs#L243

Determine why koop will not return a "Multipoint" result to the ArcMap.

Sample Feature Descriptor:
```
{
  "info" : {
    "name" : "Multipoint",
    "description" : "Multipoint Example"
  },

  "layers" : [
    {
      "id": 0,
      "name" : "Objects",
      "decription": "All Objects",
      "geometryType": "Point",
      "idField": "OBJECTID",
      "displayField": "LABEL",
      "geometryPath": "/geometry",
      "extent": {
        "xmin": -180,
        "ymin": -90,
        "xmax": 180,
        "ymax": 90,
        "spatialReference": {
          "wkid": 4326,
          "latestWkid": 4326
        }
      },
      "schema" : "Multipoint",
      "view" : "Objects",
      "geometry" : {
        "type" : "Point",
        "format" : "custom",
        "coordinateSystem" : "wgs84",
        "xpath" : "//*:objectPropertyLocation",
        "indexes": {
          "elementChild": [
            {
              "parentNamespaceUri": "",
              "parentLocalname": "_metadata",
              "namespaceUri": "",
              "localname": "objectPropertyLocation",
              "pointFormat": "point",
              "coordinateSystem": "wgs84"
            }
          ]
        }
      }
    }
  ]
}
```

**Comment by prestonmcgowan** [comment] 2019-09-04 20:27
Hack of Multipoint to Point

```
this.extract = function (result) {
    const resultGeometry = {
      type : "Point", //HACK: was "MultiPoint"
      coordinates : []
    }

    if (result.geometry) {
    const extracted = result.geometry.toObject();
    const lonLat = (extracted.pointFormat === "long-lat-point");

    let points = extracted.points;
    for (const point of points) {
          const parts = point.valueOf().trim().split(/\s*,\s*|\s+/, 2);
          if (lonLat) {
            //HACK resultGeometry.coordinates.push([ Number(parts[0]), Number(parts[1])]);
            resultGeometry.coordinates.push(Number(parts[0]));
            resultGeometry.coordinates.push(Number(parts[1]));
          } else {
            //HACK resultGeometry.coordinates.push([ Number(parts[1]), Number(parts[0])]);
            resultGeometry.coordinates.push(Number(parts[1]));
            resultGeometry.coordinates.push(Number(parts[0]));
          }
          //HACK
          break;
      }

    result.geometry = resultGeometry;
    }
    return result;
  }
}
```

**Comment by jkerr5** [comment] 2020-02-10 23:02
Koop should support the following for `geometryType` though: `Point || MultiPoint || LineString || MultiLineString || Polygon || MultiPolygon`

Maybe the issue is that the service descriptor sets the `geometryType` to `Point` but the GeoJSON returned is actually `MultiPoint`?

**Comment by mfgumban** [comment] 2020-04-01 06:42
A related issue to this one is the code assumes it has multiple custom indexes to loop against, so a single custom index results in a JS error `result.geometry.toArray is not a function`.  This is fixed and will be part of the next release.
 
There is a disconnect between what you can set in `geometryType` and the number of custom indexes you can configure in the service descriptor, so one could set the former to `Point` but declare more than one index, which results in multiple extracted points.  Since the extractor uses XPath, there is also a chance it will retrieve multiple points depending on how the document is structured.

I would argue that the service should follow `geometryType` and adjust its behavior accordingly.

If `geometryType` set as `Point`:

- it will output `Point` features regardless of how many get extracted (use the 1st extracted point).
- it will log warnings if it detects multiple extracted points so the developer can fix the descriptor or indexes.

If `geometryType` is `MultiPoint`, no issues on how many points get extracted.

On why ArcMap (or even ArcGIS Online) seems to have weird behavior when trying to consume `MultiPoint` features would be a separate investigation.

**Closed** 2020-05-12 06:42 UTC
